const mongoose=require('mongoose');
const Schema=mongoose.Schema({
  BuildingId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"tenants",
    required:true
  },
  UnitId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"tenants",
    required:true
  },
  TenantId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"tenants",
    required:true
  },
  ExpertId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"experts",
    required:true
  },
  ExpenseItem:{
    type:String,
    enum:["AC","Fan","Laptop","Furniture","Inverter"],
    required:true
  },
  Currency:{
    type:String,
    enum:["$","INR"],
    required:true
  },
  ExpensesAmount:{
    type:Number,
    required:true,
  },
  Date:{
    type:Date,
    required:true
  },
  Remark:{
    type:String
  },
  Images:{
    type:String
  }
})
const Expenses=mongoose.model('expenses',Schema);
module.exports=Expenses