const mongoose=require('mongoose');
const Schema=mongoose.Schema({
  BuildingId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"expenses",
    required:true
  },
  UnitId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"expenses",
    required:true
  },
  TenantId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"expenses",
    required:true
  },
  AssignExpertId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"expenses",
    required:true
  },
  RequestStatus:{
    type:String,
    enum:["Raised","Due"],
    required:true
  },
  RequestForId:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"expenses",
    required:true
  },
  RequestDateId:{
    type:Date,
    ref:"expenses",
    required:true
  },
  Description:{
    type:String
  },
  Images:{
    type:String
  }
})
const Maintain=mongoose.model('maintains',Schema);
module.exports=Maintain